# Inspired by http://sachachua.com/blog/2015/02/continuous-integration-code-coverage-emacs-packages-travis-coveralls/

language: emacs-lisp

env:
  matrix:
    - EMACS=emacs23
    - EMACS=emacs24
    - EMACS=emacs25
    - EMACS=emacs-snapshot

before_install:
  # PPA for stable Emacs packages
  - sudo add-apt-repository -y ppa:cassou/emacs
  # PPA for Emacs nightlies
  - sudo add-apt-repository -y ppa:ubuntu-elisp/ppa
  # Update and install the Emacs for our environment
  - sudo apt-get update -qq
  - sudo apt-get install -qq -yy ${EMACS}-nox ${EMACS}-el

script:
  $EMACS --version
  make elc
  make indent-test EMACS="$EMACS"

notifications:
  email: true
